// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://notyhakhjrmzhnnjbiqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vdHloYWtoanJtemhubmpiaXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTg1MTgsImV4cCI6MjA2NjU3NDUxOH0.l5yHvuD7ruZuwDyiatihGFxapNB7VbHN9AMkddyHFCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);